<?php

Route::group(['prefix' => 'Master',  'middleware' => 'auth:admin'], function () {
    Route::get('index', [App\Http\Controllers\Master\MasterController::class, 'index']);

    ////////////// Employee //////////////////////////////////////////
    Route::get('Add_Employee/{id?}', [App\Http\Controllers\Master\MasterEmployeeController::class, 'Add_Employee']);
    Route::get('Remove_Employee/{id?}', [App\Http\Controllers\Master\MasterEmployeeController::class, 'Remove_Employee']);
    Route::post('store_Employee', [App\Http\Controllers\Master\MasterEmployeeController::class, 'store_Employee']);
    Route::get('delete_Employee/{id}', [App\Http\Controllers\Master\MasterEmployeeController::class, 'delete_Employee']);
    Route::get('Assign_Step/{id?}', [App\Http\Controllers\Master\MasterEmployeeController::class, 'Assign_Step']);
    Route::post('store_Assign_Step', [App\Http\Controllers\Master\MasterEmployeeController::class, 'store_Assign_Step']);
    Route::get('delete_Assign_Step/{id}', [App\Http\Controllers\Master\MasterEmployeeController::class, 'delete_Assign_Step']);

    /////////////// Address ////////////////////////////////////////
    Route::get('country/{id?}', [App\Http\Controllers\Master\MasterAddressController::class, 'country']);
    Route::post('country_store', [App\Http\Controllers\Master\MasterAddressController::class, 'country_store']);
    Route::get('delete_country/{id}', [App\Http\Controllers\Master\MasterAddressController::class, 'delete_country']);
    Route::get('state/{id?}', [App\Http\Controllers\Master\MasterAddressController::class, 'state']);
    Route::post('state_store', [App\Http\Controllers\Master\MasterAddressController::class, 'state_store']);
    Route::get('delete_state/{id}', [App\Http\Controllers\Master\MasterAddressController::class, 'delete_state']);
    Route::get('district/{id?}', [App\Http\Controllers\Master\MasterAddressController::class, 'district']);
    Route::post('district_store', [App\Http\Controllers\Master\MasterAddressController::class, 'district_store']);
    Route::get('delete_district/{id}', [App\Http\Controllers\Master\MasterAddressController::class, 'delete_district']);
    Route::get('organization/{id?}', [App\Http\Controllers\Master\MasterAddressController::class, 'organization']);
    Route::post('organization_store', [App\Http\Controllers\Master\MasterAddressController::class, 'organization_store']);
    Route::get('delete_organization/{id}', [App\Http\Controllers\Master\MasterAddressController::class, 'delete_organization']);
    Route::get('name_of_unit/{id?}', [App\Http\Controllers\Master\MasterAddressController::class, 'name_of_unit']);
    Route::post('name_of_unit_store', [App\Http\Controllers\Master\MasterAddressController::class, 'name_of_unit_store']);
    Route::get('delete_nameofunit/{id}', [App\Http\Controllers\Master\MasterAddressController::class, 'delete_nameofunit']);
    Route::get('Employee_Type/{id?}', [App\Http\Controllers\Master\MasterAddressController::class, 'Employee_Type']);
    Route::post('Employee_Type_store', [App\Http\Controllers\Master\MasterAddressController::class, 'Employee_Type_store']);
    Route::get('delete_Employee_Type/{id}', [App\Http\Controllers\Master\MasterAddressController::class, 'delete_Employee_Type']);

    /////////////Statutory///////////////
    Route::get('factory_license/{id?}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'factory_license']);
    Route::post('factory_license_store', [App\Http\Controllers\Master\MasterStatutoryController::class, 'factory_license_store']);
    Route::get('delete_factory_license/{id}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'delete_factory_license']);
    Route::get('GST/{id?}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'GST']);
    Route::post('GST_store', [App\Http\Controllers\Master\MasterStatutoryController::class, 'GST_store']);
    Route::get('delete_GST/{id}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'delete_GST']);
    Route::get('labour_license/{id?}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'labour_license']);
    Route::post('labour_license_store', [App\Http\Controllers\Master\MasterStatutoryController::class, 'labour_license_store']);
    Route::get('delete_labour_license/{id}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'delete_labour_license']);
    Route::get('pan/{id?}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'pan']);
    Route::post('pan_store', [App\Http\Controllers\Master\MasterStatutoryController::class, 'pan_store']);
    Route::get('delete_pan/{id}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'delete_pan']);
    Route::get('polution_certificate/{id?}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'polution_certificate']);
    Route::post('polution_certificate_store', [App\Http\Controllers\Master\MasterStatutoryController::class, 'polution_certificate_store']);
    Route::get('delete_polution_certificate/{id}', [App\Http\Controllers\Master\MasterStatutoryController::class, 'delete_polution_certificate']);

    //////////////Plan and Machinery///////////
    Route::get('plant_name/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'plant_name']);
    Route::post('plant_name_store', [App\Http\Controllers\Master\MasterPlantController::class, 'plant_name_store']);
    Route::get('delete_plantname/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_plantname']);
    Route::get('product/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'product']);
    Route::post('product_store', [App\Http\Controllers\Master\MasterPlantController::class, 'product_store']);
    Route::get('delete_product/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_product']);
    Route::get('Subproduct/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Subproduct']);
    Route::post('Subproduct_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Subproduct_store']);
    Route::get('delete_Subproduct/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Subproduct']);
    Route::get('subsubproduct/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'subsubproduct']);
    Route::post('subsubproduct_store', [App\Http\Controllers\Master\MasterPlantController::class, 'subsubproduct_store']);
    Route::get('delete_subsubproduct/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_subsubproduct']);
    Route::get('uoms/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'uoms']);
    Route::post('uoms_store', [App\Http\Controllers\Master\MasterPlantController::class, 'uoms_store']);
    Route::get('delete_uoms/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_uoms']);
    Route::get('Accessories/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Accessories']);
    Route::post('Accessories_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Accessories_store']);
    Route::get('delete_Accessories/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Accessories']);
    Route::get('Duration/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Duration']);
    Route::post('Duration_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Duration_store']);
    Route::get('delete_Duration/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Duration']);
    Route::get('Machine_Code/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Machine_Code']);
    Route::post('Machine_Code_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Machine_Code_store']);
    Route::get('delete_Machine_Code/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Machine_Code']);
    Route::get('Make_Model/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Make_Model']);
    Route::post('Make_Model_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Make_Model_store']);
    Route::get('delete_Make_Model/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Make_Model']);
    Route::get('Production_Capacity/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Production_Capacity']);
    Route::post('Production_Capacity_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Production_Capacity_store']);
    Route::get('delete_Production_Capacity/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Production_Capacity']);
    Route::get('Specification/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Specification']);
    Route::post('Specification_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Specification_store']);
    Route::get('delete_Specification/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Specification']);
    Route::get('Warranty/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Warranty']);
    Route::post('Warranty_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Warranty_store']);
    Route::get('delete_Warranty/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Warranty']);
    Route::get('Machine_Name/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Machine_Name']);
    Route::post('Machine_Name_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Machine_Name_store']);
    Route::get('delete_Machine_Name/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Machine_Name']);
    Route::get('Manufacturing_unit/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Manufacturing_unit']);
    Route::post('Manufacturing_unit_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Manufacturing_unit_store']);
    Route::get('delete_Manufacturing_unit/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Manufacturing_unit']);
    Route::get('BU/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'BU']);
    Route::post('BU_store', [App\Http\Controllers\Master\MasterPlantController::class, 'BU_store']);
    Route::get('delete_BU/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_BU']);
    Route::get('quality_check/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'quality_check']);
    Route::post('quality_check_store', [App\Http\Controllers\Master\MasterPlantController::class, 'quality_check_store']);
    Route::get('delete_quality_check/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_quality_check']);
    Route::get('category/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'category']);
    Route::post('category_store', [App\Http\Controllers\Master\MasterPlantController::class, 'category_store']);
    Route::get('delete_category/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_category']);
    Route::get('Company_Name/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Company_Name']);
    Route::post('Company_Name_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Company_Name_store']);
    Route::get('delete_Company_Name/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Company_Name']);
    Route::get('Customer_Name/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Customer_Name']);
    Route::post('Customer_Name_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Customer_Name_store']);
    Route::get('delete_Customer_Name/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Customer_Name']);
    Route::get('Work_Order_Status/{id?}', [App\Http\Controllers\Master\MasterPlantController::class, 'Work_Order_Status']);
    Route::post('Work_Order_Status_store', [App\Http\Controllers\Master\MasterPlantController::class, 'Work_Order_Status_store']);
    Route::get('delete_Work_Order_Status/{id}', [App\Http\Controllers\Master\MasterPlantController::class, 'delete_Work_Order_Status']);

    ////////land & building////////////////
    Route::get('land_type/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'land_type']);
    Route::post('land_type_store', [App\Http\Controllers\Master\MasterLandController::class, 'land_type_store']);
    Route::get('delete_landtype/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_landtype']);
    Route::get('BoundaryHeight/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'BoundaryHeight']);
    Route::post('BoundaryHeight_store', [App\Http\Controllers\Master\MasterLandController::class, 'BoundaryHeight_store']);
    Route::get('delete_BoundaryHeight/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_BoundaryHeight']);
    Route::get('BoundaryType/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'BoundaryType']);
    Route::post('BoundaryType_store', [App\Http\Controllers\Master\MasterLandController::class, 'BoundaryType_store']);
    Route::get('delete_BoundaryType/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_BoundaryType']);
    Route::get('BoundaryWidth/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'BoundaryWidth']);
    Route::post('BoundaryWidth_store', [App\Http\Controllers\Master\MasterLandController::class, 'BoundaryWidth_store']);
    Route::get('delete_BoundaryWidth/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_BoundaryWidth']);
    Route::get('BuildingArea/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'BuildingArea']);
    Route::post('BuildingArea_store', [App\Http\Controllers\Master\MasterLandController::class, 'BuildingArea_store']);
    Route::get('delete_BuildingArea/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_BuildingArea']);
    Route::get('BuildingType/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'BuildingType']);
    Route::post('BuildingType_store', [App\Http\Controllers\Master\MasterLandController::class, 'BuildingType_store']);
    Route::get('delete_BuildingType/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_BuildingType']);
    Route::get('CoverArea/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'CoverArea']);
    Route::post('CoverArea_store', [App\Http\Controllers\Master\MasterLandController::class, 'CoverArea_store']);
    Route::get('delete_CoverArea/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_CoverArea']);
    Route::get('Gate/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'Gate']);
    Route::post('Gate_store', [App\Http\Controllers\Master\MasterLandController::class, 'Gate_store']);
    Route::get('delete_Gate/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_Gate']);
    Route::get('LandArea/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'LandArea']);
    Route::post('LandArea_store', [App\Http\Controllers\Master\MasterLandController::class, 'LandArea_store']);
    Route::get('delete_LandArea/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_LandArea']);
    Route::get('OpenArea/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'OpenArea']);
    Route::post('OpenArea_store', [App\Http\Controllers\Master\MasterLandController::class, 'OpenArea_store']);
    Route::get('delete_OpenArea/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_OpenArea']);
    Route::get('Window/{id?}', [App\Http\Controllers\Master\MasterLandController::class, 'Window']);
    Route::post('Window_store', [App\Http\Controllers\Master\MasterLandController::class, 'Window_store']);
    Route::get('delete_Window/{id}', [App\Http\Controllers\Master\MasterLandController::class, 'delete_Window']);


    ////////Gatepas///////////

    Route::get('employee_name/{id?}', [App\Http\Controllers\Master\MasterGatepassController::class, 'employee_name']);
    Route::post('employee_name_store', [App\Http\Controllers\Master\MasterGatepassController::class, 'employee_name_store']);
    Route::get('delete_employee_name/{id}', [App\Http\Controllers\Master\MasterGatepassController::class, 'delete_employee_name']);
    Route::get('request_type/{id?}', [App\Http\Controllers\Master\MasterGatepassController::class, 'request_type']);
    Route::post('request_type_store', [App\Http\Controllers\Master\MasterGatepassController::class, 'request_type_store']);
    Route::get('delete_request_type/{id}', [App\Http\Controllers\Master\MasterGatepassController::class, 'delete_request_type']);
    Route::get('person_to_meet/{id?}', [App\Http\Controllers\Master\MasterGatepassController::class, 'person_to_meet']);
    Route::post('person_to_meet_store', [App\Http\Controllers\Master\MasterGatepassController::class, 'person_to_meet_store']);
    Route::get('delete_person_to_meet/{id}', [App\Http\Controllers\Master\MasterGatepassController::class, 'delete_person_to_meet']);
    Route::get('request_through/{id?}', [App\Http\Controllers\Master\MasterGatepassController::class, 'request_through']);
    Route::post('request_through_store', [App\Http\Controllers\Master\MasterGatepassController::class, 'request_through_store']);
    Route::get('delete_request_through/{id}', [App\Http\Controllers\Master\MasterGatepassController::class, 'delete_request_through']);
    Route::get('department/{id?}', [App\Http\Controllers\Master\MasterGatepassController::class, 'department']);
    Route::post('department_store', [App\Http\Controllers\Master\MasterGatepassController::class, 'department_store']);
    Route::get('delete_department/{id}', [App\Http\Controllers\Master\MasterGatepassController::class, 'delete_department']);
    Route::get('contact_person/{id?}', [App\Http\Controllers\Master\MasterGatepassController::class, 'contact_person']);
    Route::post('contact_person_store', [App\Http\Controllers\Master\MasterGatepassController::class, 'contact_person_store']);
    Route::get('delete_contact_person/{id}', [App\Http\Controllers\Master\MasterGatepassController::class, 'delete_contact_person']);


    ///////// Raw Material ////////////////////////////////////
    Route::get('Godown_Name/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Godown_Name']);
    Route::post('Godown_Name_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Godown_Name_store']);
    Route::get('delete_Godown_Name/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Godown_Name']);
    Route::get('Raw_Material/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Raw_Material']);
    Route::get('View_details_material/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'View_details_material']);
    Route::post('Raw_Material_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Raw_Material_store']);
    Route::get('delete_Raw_Material/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Raw_Material']);
    Route::get('OB/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'OB']);
    Route::post('OB_store', [App\Http\Controllers\Master\RawMaterialController::class, 'OB_store']);
    Route::get('delete_OB/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_OB']);
    Route::get('Received_QTY/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Received_QTY']);
    Route::post('Received_QTY_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Received_QTY_store']);
    Route::get('delete_Received_QTY/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Received_QTY']);
    Route::get('Rack_No/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Rack_No']);
    Route::post('Rack_No_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Rack_No_store']);
    Route::get('delete_Rack_No/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Rack_No']);
    Route::get('Sub_Rack_No/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Sub_Rack_No']);
    Route::post('Sub_Rack_No_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Sub_Rack_No_store']);
    Route::get('delete_Sub_Rack_No/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Sub_Rack_No']);
    Route::get('Bin_No/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Bin_No']);
    Route::post('Bin_No_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Bin_No_store']);
    Route::get('delete_Bin_No/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Bin_No']);
    Route::get('Sub_Bin_No/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Sub_Bin_No']);
    Route::post('Sub_Bin_No_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Sub_Bin_No_store']);
    Route::get('delete_Sub_Bin_No/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Sub_Bin_No']);
    Route::get('Material_Name/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Material_Name']);
    Route::post('Material_Name_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Material_Name_store']);
    Route::get('delete_Material_Name/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Material_Name']);
    Route::get('HSN_Code/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'HSN_Code']);
    Route::post('HSN_Code_store', [App\Http\Controllers\Master\RawMaterialController::class, 'HSN_Code_store']);
    Route::get('delete_HSN_Code/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_HSN_Code']);
    Route::get('Gate_Pass_Required/{id?}', [App\Http\Controllers\Master\RawMaterialController::class, 'Gate_Pass_Required']);
    Route::post('Gate_Pass_Required_store', [App\Http\Controllers\Master\RawMaterialController::class, 'Gate_Pass_Required_store']);
    Route::get('delete_Gate_Pass_Required/{id}', [App\Http\Controllers\Master\RawMaterialController::class, 'delete_Gate_Pass_Required']);


    ///////// BOM //////////////////////////////////
    Route::get('Code/{id?}', [App\Http\Controllers\Master\MasterBOMController::class, 'Code']);
    Route::post('Code_store', [App\Http\Controllers\Master\MasterBOMController::class, 'Code_store']);
    Route::get('delete_Code/{id}', [App\Http\Controllers\Master\MasterBOMController::class, 'delete_Code']);
    Route::get('Color/{id?}', [App\Http\Controllers\Master\MasterBOMController::class, 'Color']);
    Route::post('Color_store', [App\Http\Controllers\Master\MasterBOMController::class, 'Color_store']);
    Route::get('delete_Color/{id}', [App\Http\Controllers\Master\MasterBOMController::class, 'delete_Color']);
    Route::get('Consumbles/{id?}', [App\Http\Controllers\Master\MasterBOMController::class, 'Consumbles']);
    Route::post('Consumbles_store', [App\Http\Controllers\Master\MasterBOMController::class, 'Consumbles_store']);
    Route::get('delete_Consumbles/{id}', [App\Http\Controllers\Master\MasterBOMController::class, 'delete_Consumbles']);
    Route::get('GST_Percentage/{id?}', [App\Http\Controllers\Master\MasterBOMController::class, 'GST_Percentage']);
    Route::post('GST_Percentage_store', [App\Http\Controllers\Master\MasterBOMController::class, 'GST_Percentage_store']);
    Route::get('delete_GST_Percentage/{id}', [App\Http\Controllers\Master\MasterBOMController::class, 'delete_GST_Percentage']);
    Route::get('Management_Expenses/{id?}', [App\Http\Controllers\Master\MasterBOMController::class, 'Management_Expenses']);
    Route::post('Management_Expenses_store', [App\Http\Controllers\Master\MasterBOMController::class, 'Management_Expenses_store']);
    Route::get('delete_Management_Expenses/{id}', [App\Http\Controllers\Master\MasterBOMController::class, 'delete_Management_Expenses']);
    Route::get('Material/{id?}', [App\Http\Controllers\Master\MasterBOMController::class, 'Material']);
    Route::post('Material_store', [App\Http\Controllers\Master\MasterBOMController::class, 'Material_store']);
    Route::get('delete_Material/{id}', [App\Http\Controllers\Master\MasterBOMController::class, 'delete_Material']);
    Route::get('Services/{id?}', [App\Http\Controllers\Master\MasterBOMController::class, 'Services']);
    Route::post('Services_store', [App\Http\Controllers\Master\MasterBOMController::class, 'Services_store']);
    Route::get('delete_Services/{id}', [App\Http\Controllers\Master\MasterBOMController::class, 'delete_Services']);
    Route::get('Machine_Specification/{id?}', [App\Http\Controllers\Master\MasterBOMController::class, 'Machine_Specification']);
    Route::post('Machine_Specification_store', [App\Http\Controllers\Master\MasterBOMController::class, 'Machine_Specification_store']);
    Route::get('delete_Machine_Specification/{id}', [App\Http\Controllers\Master\MasterBOMController::class, 'delete_Machine_Specification']);

});
